server:
  port: 9085
dubbo:
  application:
    name: cart-consumer
  registry:
    address: zookeeper://192.168.2.161:2181
spring:
  redis:
    host: 192.168.2.159
    port: 6379
    password: java1908
    jedis:
      pool:
        max-active: 20
